name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./

  test-tag-good:
    runs-on: ubuntu-latest
    steps:
      - uses: woodruffw-experiments/gha-trickery@good

  test-pinned-good:
    runs-on: ubuntu-latest
    steps:
      - uses: woodruffw-experiments/gha-trickery@2a6d8740b45f670eaca097355b63c23aee3c41f4

  test-pinned-good-truncated:
    runs-on: ubuntu-latest
    steps:
      - uses: woodruffw-experiments/gha-trickery@2a6d8740

  test-pinned-good-truncated-longer:
    runs-on: ubuntu-latest
    steps:
      - uses: woodruffw-experiments/gha-trickery@2a6d8740b45f67
